# Render Blueprint - Best Lap (Unified API + Dashboard)
# Deploys both API (Docker) and Dashboard (Static Site) together
# Documentation: https://render.com/docs/blueprint-spec
#
# Architecture:
# - Render.com: API + Dashboard (auto-deploy, HTTPS, CDN)
# - AWS EC2: TimescaleDB + Redis + Admin + Metrics Collector
#
# Usage:
# 1. Push this file to GitHub
# 2. Render Dashboard → New → Blueprint
# 3. Select repository and this file
# 4. Configure environment variables (see below)
# 5. Apply

services:
  # ============================================
  # API Backend (Docker)
  # ============================================
  - type: web
    name: best-lap-api
    env: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    region: ohio  # us-east-2 (closer to EC2 us-east-1)
    plan: free    # or "starter" ($7/mês, no cold starts)
    healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: production

      - key: API_PORT
        value: 3333

      # Database (EC2) - MUST UPDATE!
      - key: DB_HOST
        sync: false  # Set manually in Render UI
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: best_lap
      - key: DB_PASSWORD
        value: best_lap
      - key: DB_NAME
        value: best_lap_db

      # Redis (EC2) - MUST UPDATE!
      - key: REDIS_HOST
        sync: false  # Set manually in Render UI
      - key: REDIS_PORT
        value: 6379

      # External APIs
      - key: GOOGLE_API_KEY
        sync: false  # Optional

      # CORS - Set manually or use wildcard for testing
      - key: CORS_ORIGIN
        value: "*"  # Change to specific domain after dashboard deploy

      # Swagger
      - key: FORCE_HTTP_SWAGGER
        value: false

  # ============================================
  # Dashboard Frontend (Static Site)
  # ============================================
  - type: web
    name: best-lap-dashboard
    runtime: static
    env: static
    plan: free

    rootDir: .
    buildCommand: bash apps/web/render-build.sh
    staticPublishPath: apps/web/dist

    # Security headers
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable

    # SPA routing
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    envVars:
      # API URL - Set manually after API deploy
      - key: VITE_API_URL
        sync: false  # Set to https://best-lap-api.onrender.com in Render UI

      - key: NODE_VERSION
        value: "20"

      - key: PNPM_VERSION
        value: "8.14.0"

      - key: NODE_ENV
        value: production

# Auto-deploy on push to main branch
